# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build for test only"
  lane :build_for_test do
    gradle(
        task: "clean"
      )
    build_android_app(
      task: "bundle", 
      build_type: "Release",
      properties: {
        "android.injected.version.code" => 2,
        "android.injected.version.name" => "1.0.3",
      }
    )
  end
  
  desc "Distribute Available Build"
  lane :distribute do
      firebase_app_distribution(
          app: "1:68666555337:android:f308ef272eb673b9f48618",
          # change to group tester
          groups: "testers",
          release_notes: "Fastlane upload test",
          android_artifact_type: "AAB",
          android_artifact_path: "../build/app/outputs/bundle/release/app-release.aab"
      )
  end

  desc "Deploy to PlayStore"
  lane :deploy_android do |options|
    upload_to_play_store(
      track: options[:production] ? "production" : options[:internal] ? "internal" : options[:alpha] ? "alpha" : "beta",
      aab: "../build/app/outputs/bundle/release/app-release.aab",
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
# TODO: Uncomment this once slack message is needed
  # lane :send_message do
  #     slack(
  #       message: "App successfully released!",
  #       channel: "#mobile-devs",  # Optional, by default will post to the default channel configured for the POST URL.
  #       success: true,        # Optional, defaults to true.
  #       # payload: {  # Optional, lets you specify any number of your own Slack attachments.
  #       #   "Build Date" => Time.new.to_s,
  #       #   "Built by" => "Jenkins",
  #       # },
  #       username: "Dev Deployment",
  #       slack_url: "elemesid.slack.com",
  #       # default_payloads: [:git_branch, :git_author], # Optional, lets you specify default payloads to include. Pass an empty array to suppress all the default payloads.
  #       # attachment_properties: { # Optional, lets you specify any other properties available for attachments in the slack API (see https://api.slack.com/docs/attachments).
  #       #      # This hash is deep merged with the existing properties set using the other properties above. This allows your own fields properties to be appended to the existing fields that were created using the `payload` property for instance.
  #       #   thumb_url: "http://example.com/path/to/thumb.png",
  #       #   fields: [{”
  #       #     title: "My Field",
  #       #     value: "My Value",
  #       #     short: true
  #       #   }]
  #       # }
  #     )
  end
end


